name: Run AIHawk Job Applier

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * *'

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.2.2

      - name: Set up Python
        uses: actions/setup-python@v5.3.0
        with:
          python-version: '3.10'

      - name: Install Ubuntu 24.04 Chrome Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            xvfb \
            libnss3 \
            libatk1.0-0 \
            libatk-bridge2.0-0 \
            libcups2 \
            libdrm2 \
            libxkbcommon0 \
            libxcomposite1 \
            libxdamage1 \
            libxrandr2 \
            libgbm1 \
            libasound2t64 \
            fonts-liberation \
            libu2f-udev \
            libvulkan1 \
            xdg-utils

      - name: Install Google Chrome Web Browser
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb
          sudo apt-get install -f -y

      - name: Install Python Dependencies
        run: |
          pip install -r requirements.txt

      - name: Launch Bot via Virtual Display Screen
        env:
          llm_api_key: ${{ secrets.GEMINI_API_KEY }}
          LINKEDIN_USERNAME: ${{ secrets.LINKEDIN_USERNAME }}
          LINKEDIN_PASSWORD: ${{ secrets.LINKEDIN_PASSWORD }}
        run: |
          # Use xvfb-run to provide a virtual screen layout for Chrome
          xvfb-run --auto-servernum python main.py
