name: Run AIHawk Job Applier

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * *'

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.2.2

      - name: Set up Python
        uses: actions/setup-python@v5.3.0
        with:
          python-version: '3.10'

      - name: Install Python Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Bot with Automated Answers
        env:
          llm_api_key: ${{ secrets.GEMINI_API_KEY }}
          LINKEDIN_USERNAME: ${{ secrets.LINKEDIN_USERNAME }}
          LINKEDIN_PASSWORD: ${{ secrets.LINKEDIN_PASSWORD }}
        run: |
          # 1. Pushes 'Down Arrow' then 'Enter' to choose the Application Option
          # 2. Pushes 'Enter' right away to choose the Default Resume Style
          # 3. Pushes 'Enter' to confirm the rest of the prompts
          printf "\033[B\n\n\n\n" | python main.py
